### ISSUE TITLE
#02 github를 가입하시오.

### ISSUE THREAD

**Issue by simeddk** [simeddk/GoThere#2]
### step
1. https://github.com/  에 가입한다.
2. 가입한 메일 주소를 카페(https://cafe.naver.com/sgagamedev) 과제 게시판에 올리시오 -> 보안땜시..
3.  그러면 제가 초대메일을 발송해드립니다.

![Image](https://user-images.githubusercontent.com/65766852/208289983-b14b9a3e-1257-40e1-9d7a-6266b6221ab0.png)

4. 초대를 수락
5. 그럼 이곳에 아래에 댓글을 달 수 있게 됨. 댓글 하나씩 남기기

**Comment by someddk2** [comment]
댓글 예시 - 김경석 : 가입완료했습니돠.

**Comment by skacjstk** [comment]
예

**Comment by jhdwktk** [comment]
????

**Comment by Pray34** [comment]
예

**Comment by simeddk** [comment]
### Header
## Header2

**Comment by Mrhoony** [comment]
github
