### ISSUE TITLE
#16 마지막주

### ISSUE THREAD

**Issue by simeddk** [simeddk/GoThere#29]
https://github.com/jojoldu/junior-recruit-scheduler#readme

기회는 공평하지 않지만 스스로 만들지 않는 자에게는 아예 찾아오지 않는다.

## 종강 이후
- HRD-NET에서 수강후기 올려주시면 됨(가급적 기분 좋은 날 기분 좋게 올려주면 좋겠음)
- 30일 이내에 올려야 마지막 차수 지원금이 지급됨(즉, 돈이 인질임)

## 앞으로?(미취업자)
# 바로 놀지 말기
- 미비된 부분이 있으면 반성을 하고, 계획표를 짠 후 -> 최소 프로젝트라도 생성을 해 놓은 후 쉴 것

### 포트폴리오
- 완성이 안되어 있으면 꼭 완성시키기
- 단, 완성의 기준을 잡을 것. 본인이 어필하고자 하는 분야를 정한 후 해당 부분까지 마무리 짓기
- 그 외에 미비된 부분은 기술문서나 용어 위주로 정리해놓기. 혹은 Todo list에 올릴 것

### 이력서
- 이력서는 메일 보내주면 다시 봐주겠음(내 일정 상 거의 주말에 봐주게 될 것 같음)
- 피드백 했던 내용은 반드시 보강할 것
- 소리내서 읽어보고 어색하지 않을 수준까지 작성할 것

### 면접
- 각 재지 말고, 연습한다 생각하고 무조건 많이 다녀보기(처음에는 신생업체, 소규모, 좉소 가리지 말 것)

### 코딩 테스트
- 프로그래머스, 백준에서 시간 날 때마다 하루 5문제 정도 계속 풀어보기(맞던 틀리던)
- 뱃지 획득하면 깃허브 프로필에 어타치시켜 버리기

## 앞으로?(취업자)
- 취업했다고 끝이 아니고 근로계약서 및 건강보험자격득실 여부 등 고용노동부에 제출해야 할 서류가 있음
- 학원에서 전화 오면 잘 받아주기(나는 안할거임)
- 최종합격 후 입사일까지 시간이 남아 있다면, 학원 홍보차 취업자 인터뷰 등을 요청할 수도 있음(내가 안함)

**Comment by skacjstk** [comment]
1. 목표: SaveGame 오브젝트를 이용해, 플레이어의 인벤토리, 장착했던 룬 저장하기
2. 성공, 구현에 성공했다. https://github.com/skacjstk/CinderGuy/tree/SaveGame

3. 고찰: 빠르게 구현한다고 Blueprint로 구현했는데, 어째서인지 가끔 execIsValid() 를 불러오지 못해 저장이 터진다.
-콜 스택을 따라가보니 대충 Blueprint 버전의 IsValid()를 호출해 Native로 넘어가 실행하는 것 같은데, 가끔 터지는거라
고민하다가 혹시나 해서 bool return 버전의 함수 IsValid() 를 사용하니 오류가 사라졌다. ( 50번 시도해서 괜찮았음 )

어쨋든, 인벤토리, 룬 인벤토리를 가져와 담아놓고, 불러왔다. 
SaveGame 상상 이상으로 편하다...

**Comment by Mrhoony** [comment]
1. 목표 : 프로토타입 구현
2. 결과 : [멀티플레이 시연영상](https://youtu.be/fMHnsJLCCF4)
3. 고찰 : 만들고 싶은 건 많은데 시간이 부족하다.

**Comment by silberstar** [comment]
1. 목표 : 캐릭터 스킬, 작물 성장, 

2. 결과 : 스폰 후 틱 함수 따라서 스케일 값을 키우는 형식으로 구현함

3.고찰 : 주말마다 듣는 유니티 강의가 저저번주에 끝나서 시간이 생긴만큼 빡시게 달렸는데 결과물이 마법사 적 캐릭터 하나, 맵 오브젝트, 풀떼기... 적어도 스테이지 하나정도는 해야 완성이라고 생각하고 있었는데 아예 전부 혼자 제작하는게 목표라 에셋까지 직접 모델링하는게 시간을 다 잡아먹은거같습니다.
