### ISSUE TITLE
#03 집에 Github Desktop 설치

### ISSUE THREAD

**Issue by simeddk** [simeddk/GoThere#6]
### 집에 설치
***
1. Git.exe 서비스를 설치(이미 설치 되어 있다면 할 필요X) https://git-scm.com/downloads
2. github desktop을 설치 https://desktop.github.com/
3. 로컬리포지토리 생성
4. 현재 작업 중인 포트폴리오 프로젝트를 로컬리포지토리로 이전하기
5. .gitignore 세팅하기 
> https://gitignore.io 
> UnrealEngine 타이핑 후 엔터
> 코드 복사 후 
> github desktip -> Repository -> Repository Settings -> Ignore Files에 붙여넣기 
7. 커밋하기
8. 푸쉬하기
9. 리모트 리포지토리 주소를 댓글로 남기기 (github desktop 에서 `ctrl` + `shift` + `G` 키를 이용해서 올 수 있음)

여기서 주의할 점은, 혹시 bulidData 라이팅맵은 100MB가 넘을 수 있다.
이그노어에 꼭 등록해서 푸쉬가 실패하는 불상사를 막아주기.
***
### 제출자
|이름|링크|
|:--|:--|
|`권정훈`|https://github.com/Mrhoony/Lilium|
|`김건웅`|https://github.com/KingSlime/U03_ThirdPerson|
|`김주연`|https://github.com/wontedesper/UE_ThirdPerson_RPG|
|`남석원`|https://github.com/skacjstk/MyUE4Study/tree/master/U03_ThridPerson|
|`서상원`|https://github.com/ssw980/Un_RPG|
|`유재우`|https://github.com/ooweaJ/Jaewoo|
|`윤대영`|[silberstar](https://github.com/silberstar?tab=repositories)|
|`이규원`|https://github.com/triglan/U03_ThirdPerson|
|`이해용`|https://github.com/Pray34/Project_A_Demo|
|`장현덕`|https://github.com/lumipia/JHD_Games|
|`최윤혁`|https://github.com/ap4ril/TurnST|
|`한수빈`|https://github.com/klpy87/U03_ThridPerson|

**Comment by simeddk** [comment]
댓글 예 : 
> 김경석 : https://github.com/simeddk/U03_ThirdPerson

**Comment by skacjstk** [comment]
https://github.com/skacjstk/MyUE4Study/tree/master/U03_ThridPerson

**Comment by simeddk** [comment]
ㄴ@skacjstk [MyUE4Study](https://github.com/skacjstk/MyUE4Study) 리포지토리가 퍼블릭이 아니네요. 리포지토리 세팅에서 바꿀 수 있어요.
특별히 사유가 없다면 퍼블릭으로 열어주세요.


![Image](https://user-images.githubusercontent.com/65766852/208401522-5e7fd744-95b4-4a36-9794-dc09ba2e9578.png)

**Comment by Pray34** [comment]
https://github.com/Pray34/U03_ThirdPerson

현재 포트폴리오 프로젝트를 따로 만들지 않아서 제 깃허브에 있는 리포지터리를 클론해온 후

맵만 열어서 킨후에 저장된걸 커밋하고 푸쉬한후에 퍼블릭인걸 확인하고 링크 올렸습니다

**Comment by skacjstk** [comment]
수정완료

**Comment by triglan** [comment]
이규원 : https://github.com/triglan/U03_ThirdPerson

**Comment by ssw980** [comment]
https://github.com/ssw980/Un_RPG

포폴 프로젝트는 만들지 않고 기능들만 구현한 프로젝트만 여러개 만들어서 여기 살을 붙히겠습니다

**Comment by ap4ril** [comment]
최윤혁 : https://github.com/ap4ril/U03_ThirdPerson

**Comment by Mrhoony** [comment]
https://github.com/Mrhoony/U03_ThirdPersonCPP

**Comment by klpy87** [comment]
한수빈 : https://github.com/klpy87/U03_ThridPerson
임시로 과제파일 연결했습니다

**Comment by ooweaJ** [comment]
유재우 : https://github.com/ooweaJ/Jaewoo

**Comment by KingSlime** [comment]
https://github.com/KingSlime/U03_ThirdPerson

**Comment by Mrhoony** [comment]
https://github.com/Mrhoony/Lilium

**Comment by wontedesper** [comment]
김주연 : https://github.com/wontedesper/UE_ThirdPerson_RPG

**Comment by lumipia** [comment]
https://github.com/lumipia/JHD_Games

**Comment by lumipia** [comment]
https://github.com/lumipia/JHD_Games

**Comment by silberstar** [comment]
윤대영
https://github.com/silberstar/Project_RustedHeart
